# Generated by Django 4.2.5 on 2023-09-23 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=255)),
                ('position', models.CharField(choices=[['TK', 'Tanks'], ['HL', 'Heals'], ['DD', 'Damage Dealers'], ['MH', 'Merchants'], ['GM', 'Guildmasters'], ['QG', 'Questgivers'], ['BS', 'Blacksmiths'], ['LW', 'Leatherworkers'], ['PO', 'Potions'], ['SM', 'Spell masters']], default='TK', max_length=2)),
                ('text_ads', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Текст объявления')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('author_ads', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ads',
                'verbose_name_plural': 'Ad',
                'db_table': 'ads',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_post', models.TextField()),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('respond', models.BooleanField(default=False)),
                ('author_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_at_ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abs.ads')),
            ],
            options={
                'verbose_name': 'Posts',
                'verbose_name_plural': 'Post',
                'db_table': 'post',
            },
        ),
    ]
